# Multiple customer classes in a model

In this example, the model has three customer classes. The customer class determines the arrival distribution and service distribution.

The JSON for this built-in example can be loaded using `json2ciw.datasets.load_three_classes_model`.

## Imports

In [1]:
import json

import ciw
from rich import print

from json2ciw.datasets import load_stroke_pathway_model
from json2ciw.engine import CiwConverter, multiple_replications
from json2ciw.results import summarise_results, summarise_results_by_class, tidy_to_wide_format, tidy_to_wide_format_by_class
from json2ciw.schema import ProcessModel

## Load JSON

In [2]:
json_network = load_stroke_pathway_model()
print(json.dumps(json_network, indent=2))

{
  "name": "Stroke pathway with class-specific routing and reneging",
  "description": "Simple multi-class stroke pathway with class-specific routing, arrival, service, and reneging
distributions.",
  "customer_classes": [
    {
      "name": "tia",
      "label": "TIA"
    },
    {
      "name": "mild_moderate_stroke",
      "label": "Mild/moderate stroke"
    },
    {
      "name": "severe_stroke",
      "label": "Severe stroke"
    }
  ],
  "activities": [
    {
      "name": "Acute Stroke Unit",
      "type": "activity",
      "resource": {
        "name": "Stroke beds",
        "capacity": 12
      },
      "arrival_distribution": {
        "by_class": {
          "tia": {
            "type": "exponential",
            "parameters": {
              "rate": 2.0
            }
          },
          "mild_moderate_stroke": {
            "type": "exponential",
            "parameters": {
              "rate": 1.2
            }
          },
          "severe_stroke": {
            "type": "exponential",
            "parameters": {
              "rate": 0.6
            }
          }
        }
      },
      "service_distribution": {
        "by_class": {
          "tia": {
            "type": "exponential",
            "parameters": {
              "mean": 2.0
            }
          },
          "mild_moderate_stroke": {
            "type": "exponential",
            "parameters": {
              "mean": 4.0
            }
          },
          "severe_stroke": {
            "type": "exponential",
            "parameters": {
              "mean": 6.0
            }
          }
        }
      },
      "renege_distribution": {
        "by_class": {
          "tia": {
            "type": "uniform",
            "parameters": {
              "min": 2.0,
              "max": 6.0
            }
          },
          "mild_moderate_stroke": {
            "type": "uniform",
            "parameters": {
              "min": 4.0,
              "max": 10.0
            }
          },
          "severe_stroke": {
            "type": "uniform",
            "parameters": {
              "min": 6.0,
              "max": 12.0
            }
          }
        }
      }
    },
    {
      "name": "Rehab Unit",
      "type": "activity",
      "queue_capacity": 0,
      "resource": {
        "name": "Rehab beds",
        "capacity": 8
      },
      "service_distribution": {
        "by_class": {
          "mild_moderate_stroke": {
            "type": "exponential",
            "parameters": {
              "mean": 8.0
            }
          },
          "severe_stroke": {
            "type": "exponential",
            "parameters": {
              "mean": 14.0
            }
          }
        }
      },
      "renege_distribution": {
        "by_class": {
          "mild_moderate_stroke": {
            "type": "uniform",
            "parameters": {
              "min": 8.0,
              "max": 16.0
            }
          },
          "severe_stroke": {
            "type": "uniform",
            "parameters": {
              "min": 10.0,
              "max": 20.0
            }
          }
        }
      }
    }
  ],
  "transitions": [
    {
      "from": "Acute Stroke Unit",
      "to": "Rehab Unit",
      "probability": {
        "by_class": {
          "tia": 0.0,
          "mild_moderate_stroke": 0.6,
          "severe_stroke": 0.9
        }
      }
    },
    {
      "from": "Acute Stroke Unit",
      "to": "Exit",
      "probability": {
        "by_class": {
          "tia": 1.0,
          "mild_moderate_stroke": 0.4,
          "severe_stroke": 0.1
        }
      }
    },
    {
      "from": "Rehab Unit",
      "to": "Exit",
      "probability": 1.0
    }
  ]
}

## Validate with `ProcessModel`

In [3]:
model_instance = ProcessModel(**json_network)

In [4]:
print(model_instance)

ProcessModel(
    name='Stroke pathway with class-specific routing and reneging',
    description='Simple multi-class stroke pathway with class-specific routing, arrival, service, and reneging
distributions.',
    customer_classes=[
        CustomerClass(name='tia', label='TIA'),
        CustomerClass(name='mild_moderate_stroke', label='Mild/moderate stroke'),
        CustomerClass(name='severe_stroke', label='Severe stroke')
    ],
    activities=[
        Activity(
            name='Acute Stroke Unit',
            type='activity',
            resource=Resource(name='Stroke beds', capacity=12),
            service_distribution=ClassDistributionMap(
                by_class={
                    'tia': Distribution(type='exponential', parameters={'mean': 2.0}),
                    'mild_moderate_stroke': Distribution(type='exponential', parameters={'mean': 4.0}),
                    'severe_stroke': Distribution(type='exponential', parameters={'mean': 6.0})
                }
            ),
            arrival_distribution=ClassDistributionMap(
                by_class={
                    'tia': Distribution(type='exponential', parameters={'rate': 2.0}),
                    'mild_moderate_stroke': Distribution(type='exponential', parameters={'rate': 1.2}),
                    'severe_stroke': Distribution(type='exponential', parameters={'rate': 0.6})
                }
            ),
            renege_distribution=ClassDistributionMap(
                by_class={
                    'tia': Distribution(type='uniform', parameters={'min': 2.0, 'max': 6.0}),
                    'mild_moderate_stroke': Distribution(type='uniform', parameters={'min': 4.0, 'max': 10.0}),
                    'severe_stroke': Distribution(type='uniform', parameters={'min': 6.0, 'max': 12.0})
                }
            ),
            queue_capacity=None
        ),
        Activity(
            name='Rehab Unit',
            type='activity',
            resource=Resource(name='Rehab beds', capacity=8),
            service_distribution=ClassDistributionMap(
                by_class={
                    'mild_moderate_stroke': Distribution(type='exponential', parameters={'mean': 8.0}),
                    'severe_stroke': Distribution(type='exponential', parameters={'mean': 14.0})
                }
            ),
            arrival_distribution=None,
            renege_distribution=ClassDistributionMap(
                by_class={
                    'mild_moderate_stroke': Distribution(type='uniform', parameters={'min': 8.0, 'max': 16.0}),
                    'severe_stroke': Distribution(type='uniform', parameters={'min': 10.0, 'max': 20.0})
                }
            ),
            queue_capacity=0
        )
    ],
    transitions=[
        Transition(
            source='Acute Stroke Unit',
            target='Rehab Unit',
            probability=ClassProbabilityMap(
                by_class={'tia': 0.0, 'mild_moderate_stroke': 0.6, 'severe_stroke': 0.9}
            )
        ),
        Transition(
            source='Acute Stroke Unit',
            target='Exit',
            probability=ClassProbabilityMap(
                by_class={'tia': 1.0, 'mild_moderate_stroke': 0.4, 'severe_stroke': 0.1}
            )
        ),
        Transition(source='Rehab Unit', target='Exit', probability=1.0)
    ]
)

In [5]:
model_instance.display_diagram(include_resources=False, show_class_arrivals=True)

```mermaid
graph TD
    Arrivals_Acute_Stroke_Unit_tia("TIA</br>Time between arrivals<br/>Exponential(λ=2.0)")
    Arrivals_Acute_Stroke_Unit_mild_moderate_stroke("Mild/moderate stroke</br>Time between arrivals<br/>Exponential(λ=1.2)")
    Arrivals_Acute_Stroke_Unit_severe_stroke("Severe stroke</br>Time between arrivals<br/>Exponential(λ=0.6)")
    Acute_Stroke_Unit["Acute Stroke Unit</br>Class-specific service distributions (n=3)"]
    Rehab_Unit["Rehab Unit</br>Class-specific service distributions (n=2)</br>No queue (blocking)"]
    classDef blocking fill:#ffcccc,stroke:#cc0000,stroke-width:2px,color:#000
    class Rehab_Unit blocking
    classDef blocking fill:#ffcccc,stroke:#cc0000,stroke-width:2px,color:#000
    class Rehab_Unit blocking
 Renege_Acute_Stroke_Unit{{"Renege</br>Class-specific reneging distributions (n=3)"}}
 Renege_Rehab_Unit{{"Renege</br>Class-specific reneging distributions (n=2)"}}
    Exit(["Exit"])

    Arrivals_Acute_Stroke_Unit_tia --> Acute_Stroke_Unit
    Arrivals_Acute_Stroke_Unit_mild_moderate_stroke --> Acute_Stroke_Unit
    Arrivals_Acute_Stroke_Unit_severe_stroke --> Acute_Stroke_Unit
    Acute_Stroke_Unit -.-> Renege_Acute_Stroke_Unit
    Rehab_Unit -.-> Renege_Rehab_Unit
    Acute_Stroke_Unit ==>|TIA: 0%<br/>Mild/moderate stroke: 60%<br/>Severe stroke: 90%| Rehab_Unit
    Acute_Stroke_Unit -->|TIA: 100%<br/>Mild/moderate stroke: 40%<br/>Severe stroke: 10%| Exit
    Rehab_Unit --> Exit
```

In [6]:
#model_instance.save_diagram("example7.mmd", include_resources=False)#

In [7]:
model_instance.get_distributions_df()

,Activity,Phase,Customer Class,Customer Class Label,Distribution Type,Parameters
0,Acute Stroke Unit,Arrival,tia,TIA,Exponential,rate=2.0
1,Acute Stroke Unit,Arrival,mild_moderate_stroke,Mild/moderate stroke,Exponential,rate=1.2
2,Acute Stroke Unit,Arrival,severe_stroke,Severe stroke,Exponential,rate=0.6
3,Acute Stroke Unit,Service,tia,TIA,Exponential,mean=2.0
4,Acute Stroke Unit,Service,mild_moderate_stroke,Mild/moderate stroke,Exponential,mean=4.0
5,Acute Stroke Unit,Service,severe_stroke,Severe stroke,Exponential,mean=6.0
6,Acute Stroke Unit,Renege,tia,TIA,Uniform,"min=2.0, max=6.0"
7,Acute Stroke Unit,Renege,mild_moderate_stroke,Mild/moderate stroke,Uniform,"min=4.0, max=10.0"
8,Acute Stroke Unit,Renege,severe_stroke,Severe stroke,Uniform,"min=6.0, max=12.0"
9,Rehab Unit,Service,mild_moderate_stroke,Mild/moderate stroke,Exponential,mean=8.0
10,Rehab Unit,Service,severe_stroke,Severe stroke,Exponential,mean=14.0
11,Rehab Unit,Renege,mild_moderate_stroke,Mild/moderate stroke,Uniform,"min=8.0, max=16.0"
12,Rehab Unit,Renege,severe_stroke,Severe stroke,Uniform,"min=10.0, max=20.0"

In [8]:
model_instance.get_routing_matrix_df()

                                        Acute Stroke Unit  Rehab Unit  Exit
Customer Class       Source Activity
tia                  Acute Stroke Unit                0.0         0.0   1.0
                     Rehab Unit                       0.0         0.0   1.0
mild_moderate_stroke Acute Stroke Unit                0.0         0.6   0.4
                     Rehab Unit                       0.0         0.0   1.0
severe_stroke        Acute Stroke Unit                0.0         0.9   0.1
                     Rehab Unit                       0.0         0.0   1.0

In [9]:
model_instance.get_resources_df()

      Resource           Activity  Count
0  Stroke beds  Acute Stroke Unit     12
1   Rehab beds         Rehab Unit      8

## Convert to `ciw` parameters

In [10]:
adapter = CiwConverter(model_instance)
network_params = adapter.generate_params()
print(network_params)

{
    'number_of_servers': [12, 8],
    'arrival_distributions': {
        'tia': [Exponential(rate=2.0), None],
        'mild_moderate_stroke': [Exponential(rate=1.2), None],
        'severe_stroke': [Exponential(rate=0.6), None]
    },
    'service_distributions': {
        'tia': [Exponential(rate=0.5), Deterministic(value=0.0)],
        'mild_moderate_stroke': [Exponential(rate=0.25), Exponential(rate=0.125)],
        'severe_stroke': [Exponential(rate=0.16666666666666666), Exponential(rate=0.07142857142857142)]
    },
    'routing': {
        'tia': [[0.0, 0.0], [0.0, 0.0]],
        'mild_moderate_stroke': [[0.0, 0.6], [0.0, 0.0]],
        'severe_stroke': [[0.0, 0.9], [0.0, 0.0]]
    },
    'reneging_time_distributions': {
        'tia': [Uniform(lower=2.0, upper=6.0), None],
        'mild_moderate_stroke': [Uniform(lower=4.0, upper=10.0), Uniform(lower=8.0, upper=16.0)],
        'severe_stroke': [Uniform(lower=6.0, upper=12.0), Uniform(lower=10.0, upper=20.0)]
    },
    'queue_capacities': [inf, 0]
}

In [11]:
# import math
# network_params["queue_capacities"] = [math.inf, math.inf]

## Build and run the `ciw` model

In [12]:
network = ciw.create_network(**network_params)
sim = ciw.Simulation(network)
sim.simulate_until_max_time(50)
print("Quick simulation run worked!")

Quick simulation run worked!

## Run the model for multiple replications

In [13]:
df_reps, df_transfers = multiple_replications(
    network,
    model_instance,
    num_reps=5,
    runtime=2880,
    warmup=1440,
    n_jobs=-1,
)

df_reps.head()

,rep,node_id,activity_name,resource_name,resource_capacity,measure_scope,customer_class,n_service,mean_wait,mean_service,mean_Lq,utilisation,n_renege,renege_rate,mean_wait_renege,mean_wait_all
0,0,1,Acute Stroke Unit,Stroke beds,12,overall,All,1912,5.499618,4.588140,18.485348,99.806409,3559,0.650521,4.524763,4.865454
1,0,1,Acute Stroke Unit,Stroke beds,12,customer_class,tia,351,4.001414,2.106673,7.964634,NaN,2603,0.881178,3.866530,3.882557
2,0,1,Acute Stroke Unit,Stroke beds,12,customer_class,mild_moderate_stroke,936,5.680708,4.161410,7.027948,NaN,793,0.458647,6.056875,5.853236
3,0,1,Acute Stroke Unit,Stroke beds,12,customer_class,severe_stroke,625,6.069808,6.620803,3.492766,NaN,163,0.206853,7.582530,6.382719
4,0,2,Rehab Unit,Rehab beds,8,overall,All,1093,0.000000,10.248982,0.000000,99.250806,0,0.000000,0.000000,0.000000

In [14]:
df_transfers.head(3)

,rep,measure_scope,customer_class,source_node_id,source_activity_name,destination_node_id,destination_activity_name,n_transfers,n_blocked,blocking_probability,mean_blocking_delay,mean_blocking_delay_given_blocked
0,0,overall,All,1,Acute Stroke Unit,2,Rehab Unit,1091,1042,0.955087,7.569610,7.925570
1,0,customer_class,mild_moderate_stroke,1,Acute Stroke Unit,2,Rehab Unit,526,499,0.948669,7.197523,7.586968
2,0,customer_class,severe_stroke,1,Acute Stroke Unit,2,Rehab Unit,565,543,0.961062,7.916013,8.236735

## Convert to wide format

In [15]:
# overall results
wide = tidy_to_wide_format(df_reps)
wide.head()

,mean_Lq [Acute Stroke Unit],mean_Lq [Rehab Unit],mean_service [Acute Stroke Unit],mean_service [Rehab Unit],mean_wait [Acute Stroke Unit],mean_wait [Rehab Unit],mean_wait_all [Acute Stroke Unit],mean_wait_all [Rehab Unit],mean_wait_renege [Acute Stroke Unit],mean_wait_renege [Rehab Unit],n_renege [Acute Stroke Unit],n_renege [Rehab Unit],n_service [Acute Stroke Unit],n_service [Rehab Unit],renege_rate [Acute Stroke Unit],renege_rate [Rehab Unit],utilisation [Acute Stroke Unit],utilisation [Rehab Unit]
rep,,,,,,,,,,,,,,,,,,
0,18.485348,0.0,4.588140,10.248982,5.499618,0.0,4.865454,0.0,4.524763,0.0,3559,0,1912,1093,0.650521,0.0,99.806409,99.250806
1,19.066567,0.0,4.508293,11.769236,5.970330,0.0,5.067526,0.0,4.690196,0.0,3821,0,1597,966,0.705242,0.0,99.881742,99.410082
2,18.995171,0.0,4.568381,10.731328,5.822918,0.0,5.022594,0.0,4.666493,0.0,3769,0,1677,1058,0.692068,0.0,99.898924,99.435467
3,20.264562,0.0,4.815249,11.827013,6.477018,0.0,5.228627,0.0,4.807811,0.0,4174,0,1407,959,0.747895,0.0,99.879771,99.616655
4,18.824071,0.0,4.265621,10.665509,5.525462,0.0,4.977353,0.0,4.720011,0.0,3706,0,1740,1063,0.680499,0.0,99.690252,99.133812

In [16]:
# results by class = server strokes
wide_by_class = tidy_to_wide_format_by_class(df_reps, customer_class="severe_stroke")
wide_by_class.head()

,mean_Lq [Acute Stroke Unit],mean_Lq [Rehab Unit],mean_service [Acute Stroke Unit],mean_service [Rehab Unit],mean_wait [Acute Stroke Unit],mean_wait [Rehab Unit],mean_wait_all [Acute Stroke Unit],mean_wait_all [Rehab Unit],mean_wait_renege [Acute Stroke Unit],mean_wait_renege [Rehab Unit],n_renege [Acute Stroke Unit],n_renege [Rehab Unit],n_service [Acute Stroke Unit],n_service [Rehab Unit],renege_rate [Acute Stroke Unit],renege_rate [Rehab Unit]
rep,,,,,,,,,,,,,,,,
0,3.492766,0.0,6.620803,12.329412,6.069808,0.0,6.382719,0.0,7.582530,0.0,163,0,625,564,0.206853,0.0
1,4.257145,0.0,6.119279,14.629583,6.652773,0.0,6.966238,0.0,7.721956,0.0,258,0,622,547,0.293182,0.0
2,3.963360,0.0,5.932365,13.405014,6.416173,0.0,6.738180,0.0,7.591776,0.0,232,0,615,557,0.273908,0.0
3,4.661260,0.0,6.112189,14.477372,6.950964,0.0,7.209682,0.0,7.745902,0.0,303,0,628,568,0.325456,0.0
4,4.258655,0.0,5.812369,13.021291,6.399002,0.0,6.746384,0.0,7.604233,0.0,262,0,647,591,0.288229,0.0

In [17]:
# results by class = tias
wide_by_class = tidy_to_wide_format_by_class(df_reps, customer_class="tia")
wide_by_class.head()

,mean_Lq [Acute Stroke Unit],mean_Lq [Rehab Unit],mean_service [Acute Stroke Unit],mean_service [Rehab Unit],mean_wait [Acute Stroke Unit],mean_wait [Rehab Unit],mean_wait_all [Acute Stroke Unit],mean_wait_all [Rehab Unit],mean_wait_renege [Acute Stroke Unit],mean_wait_renege [Rehab Unit],n_renege [Acute Stroke Unit],n_renege [Rehab Unit],n_service [Acute Stroke Unit],n_service [Rehab Unit],renege_rate [Acute Stroke Unit],renege_rate [Rehab Unit]
rep,,,,,,,,,,,,,,,,
0,7.964634,0.0,2.106673,0.0,4.001414,0.0,3.882557,0.0,3.866530,0.0,2603,0,351,0,0.881178,0.0
1,7.934040,0.0,2.073117,0.0,4.205018,0.0,3.924774,0.0,3.899135,0.0,2667,0,244,0,0.916180,0.0
2,7.716067,0.0,1.770077,0.0,3.910360,0.0,3.898644,0.0,3.897630,0.0,2623,0,227,0,0.920351,0.0
3,8.009668,0.0,1.902679,0.0,4.415495,0.0,3.948621,0.0,3.926525,0.0,2789,0,132,0,0.954810,0.0
4,7.734007,0.0,2.071273,0.0,3.403590,0.0,3.881830,0.0,3.936433,0.0,2575,0,294,0,0.897525,0.0

## Summarise results

In [18]:
df_reps.head(2)

,rep,node_id,activity_name,resource_name,resource_capacity,measure_scope,customer_class,n_service,mean_wait,mean_service,mean_Lq,utilisation,n_renege,renege_rate,mean_wait_renege,mean_wait_all
0,0,1,Acute Stroke Unit,Stroke beds,12,overall,All,1912,5.499618,4.588140,18.485348,99.806409,3559,0.650521,4.524763,4.865454
1,0,1,Acute Stroke Unit,Stroke beds,12,customer_class,tia,351,4.001414,2.106673,7.964634,NaN,2603,0.881178,3.866530,3.882557

In [19]:
summary = summarise_results(df_reps)
summary.round(1)

activity,Metric,Acute Stroke Unit (Stroke beds),Rehab Unit (Rehab beds)
0,Mean completed services,1666.6,1027.8
1,Mean waiting time,5.9,0.0
2,Mean service time,4.5,11.0
3,Mean utilisation,99.8,99.4
4,Mean queue length,19.1,0.0
5,Mean reneges,3805.8,0.0
6,Mean reneging rate,0.7,0.0
7,Mean reneging wait,4.7,0.0
8,Mean wait (all customers),5.0,0.0

In [20]:
summary_class = summarise_results_by_class(df_reps)
summary_class.round(1)

,Activity,Customer Class,Mean completed services,Mean waiting time,Mean service time,Mean queue length,Mean reneges,Mean reneging rate,Mean reneging wait,Mean wait (all customers)
0,Acute Stroke Unit,mild_moderate_stroke,789.6,5.9,4.1,7.1,910.8,0.5,6.2,6.0
1,Acute Stroke Unit,severe_stroke,627.4,6.5,6.1,4.1,243.6,0.3,7.6,6.8
2,Acute Stroke Unit,tia,249.6,4.0,2.0,7.9,2651.4,0.9,3.9,3.9
3,Rehab Unit,mild_moderate_stroke,462.4,0.0,7.9,0.0,0.0,0.0,0.0,0.0
4,Rehab Unit,severe_stroke,565.4,0.0,13.6,0.0,0.0,0.0,0.0,0.0
5,Rehab Unit,tia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
transfer_summary_by_class = summarise_transfer_results(
    df_transfers,
    include_customer_class=True,
)

transfer_summary_by_class.round(2)

,Source activity,Destination activity,Customer Class,Mean transfers,Mean blocked transfers,Mean blocking probability,Mean blocking delay,Mean blocking delay (given blocked)
0,Acute Stroke Unit,Rehab Unit,Overall,1021.0,991.4,0.97,9.33,9.59
1,Acute Stroke Unit,Rehab Unit,mild_moderate_stroke,460.8,443.2,0.96,9.08,9.41
2,Acute Stroke Unit,Rehab Unit,severe_stroke,560.2,548.2,0.98,9.54,9.74